# Generated by Django 5.0.4 on 2024-04-24 00:28

import django.db.models.deletion
import main_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main_app.models.get_upload_path)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.folder')),
            ],
        ),
    ]
